speakers:
  jason:
    display_name: Jason Calacanis
    role: host
    embedding: data/speakers/jason.npy
    embedding_strategy: speechbrain
  chamath:
    display_name: Chamath Palihapitiya
    role: host
    embedding: data/speakers/chamath.npy
    embedding_strategy: speechbrain
  sacks:
    display_name: David Sacks
    role: host
    embedding: data/speakers/sacks.npy
    embedding_strategy: speechbrain
  friedberg:
    display_name: David Friedberg
    role: host
    embedding: data/speakers/friedberg.npy
    embedding_strategy: speechbrain
